# Generated by Django 5.1.15 on 2026-06-10 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(max_length=80, verbose_name='名稱')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('emoji', models.CharField(blank=True, default='🗺️', max_length=8, verbose_name='圖示')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公開')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to=settings.AUTH_USER_MODEL, verbose_name='擁有者')),
            ],
            options={
                'verbose_name': '地圖',
                'verbose_name_plural': '地圖',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(max_length=60, verbose_name='名稱')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('color', models.CharField(default='#F97316', max_length=9, verbose_name='顏色')),
                ('icon', models.CharField(blank=True, default='📍', max_length=8, verbose_name='圖示')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公開')),
                ('is_collaborative', models.BooleanField(default=False, verbose_name='是否可共編')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='maps.map', verbose_name='所屬地圖')),
            ],
            options={
                'verbose_name': '分類',
                'verbose_name_plural': '分類',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(max_length=120, verbose_name='名稱')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='地址')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='緯度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='經度')),
                ('google_maps_url', models.URLField(blank=True, max_length=500, verbose_name='Google Maps 連結')),
                ('google_place_id', models.CharField(blank=True, max_length=255, verbose_name='Google Place ID')),
                ('status', models.CharField(blank=True, default='想去', max_length=32, verbose_name='狀態')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='星等')),
                ('recommend_level', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='推薦程度')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='標籤')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('want_reason', models.TextField(blank=True, verbose_name='想去原因')),
                ('experience_note', models.TextField(blank=True, verbose_name='實際體驗紀錄')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='places/', verbose_name='照片')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='maps.category', verbose_name='所屬分類')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_places', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_places', to=settings.AUTH_USER_MODEL, verbose_name='最後更新者')),
            ],
            options={
                'verbose_name': '地點',
                'verbose_name_plural': '地點',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='maps_place_latitud_2b60c6_idx'), models.Index(fields=['status'], name='maps_place_status_cf24d2_idx')],
            },
        ),
    ]
