# Generated by Django 5.1.15 on 2026-06-10 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('role', models.CharField(choices=[('editor', '編輯者'), ('viewer', '檢視者')], default='editor', max_length=16, verbose_name='角色')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to=settings.AUTH_USER_MODEL, verbose_name='邀請者')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='maps.map', verbose_name='地圖')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to=settings.AUTH_USER_MODEL, verbose_name='共編者')),
            ],
            options={
                'verbose_name': '共編者',
                'verbose_name_plural': '共編者',
                'ordering': ['created_at'],
                'unique_together': {('map', 'user')},
            },
        ),
    ]
