# Generated by Django 5.1.15 on 2026-06-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_collaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='share_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='分享 token'),
        ),
    ]
